# Generated by Django 5.1.3 on 2024-12-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
