# Generated by Django 5.1.3 on 2024-12-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
