# Generated by Django 5.1.3 on 2024-12-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0007_alter_post_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
