# Generated by Django 5.1.3 on 2024-12-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0009_user_bio_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
