# Generated by Django 5.1.3 on 2024-12-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0011_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
